job_number: "J-25-B124"           # e.g., J-25-A134
job_folder_name: "J-25-B124 (VSR)"
sterile: true                     # controls CoC template selection
run_data_root: "\\\\srv3d\\company\\Dropbox\\2025 Run Data"
templates_map_path: './maps/MBR Template Map.xlsx'
fake_825_root: "\\\\srv3d\\company\\Dropbox\\825 - Monitoring & Measurement"
dropbox_root: ""                  # optional, can remain blank
cmd_rel_path: 'docs\CMD'               # subfolder under job folder
reset_sc_on_rerun: true           # re-copy S&C each run
